//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Fecha { get; set; }
        public string Vendedor { get; set; }
        public string Cliente { get; set; }
        public string Producto { get; set; }
    }
}
